# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Inclusive import vocab_pb2 as Inclusive_dot_vocab__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Inclusive/vocab_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VocabServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReviewCard = channel.unary_unary(
                '/vocab.VocabService/ReviewCard',
                request_serializer=Inclusive_dot_vocab__pb2.ReviewRequest.SerializeToString,
                response_deserializer=Inclusive_dot_vocab__pb2.ReviewResponse.FromString,
                _registered_method=True)
        self.AnalyzeText = channel.unary_unary(
                '/vocab.VocabService/AnalyzeText',
                request_serializer=Inclusive_dot_vocab__pb2.AnalyzeTextRequest.SerializeToString,
                response_deserializer=Inclusive_dot_vocab__pb2.AnalyzeTextResponse.FromString,
                _registered_method=True)
        self.AnalyzeTargetWord = channel.unary_unary(
                '/vocab.VocabService/AnalyzeTargetWord',
                request_serializer=Inclusive_dot_vocab__pb2.AnalyzeTargetWordRequest.SerializeToString,
                response_deserializer=Inclusive_dot_vocab__pb2.AnalyzeTargetWordResponse.FromString,
                _registered_method=True)


class VocabServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ReviewCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeTargetWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VocabServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReviewCard': grpc.unary_unary_rpc_method_handler(
                    servicer.ReviewCard,
                    request_deserializer=Inclusive_dot_vocab__pb2.ReviewRequest.FromString,
                    response_serializer=Inclusive_dot_vocab__pb2.ReviewResponse.SerializeToString,
            ),
            'AnalyzeText': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeText,
                    request_deserializer=Inclusive_dot_vocab__pb2.AnalyzeTextRequest.FromString,
                    response_serializer=Inclusive_dot_vocab__pb2.AnalyzeTextResponse.SerializeToString,
            ),
            'AnalyzeTargetWord': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeTargetWord,
                    request_deserializer=Inclusive_dot_vocab__pb2.AnalyzeTargetWordRequest.FromString,
                    response_serializer=Inclusive_dot_vocab__pb2.AnalyzeTargetWordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vocab.VocabService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vocab.VocabService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VocabService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReviewCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vocab.VocabService/ReviewCard',
            Inclusive_dot_vocab__pb2.ReviewRequest.SerializeToString,
            Inclusive_dot_vocab__pb2.ReviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vocab.VocabService/AnalyzeText',
            Inclusive_dot_vocab__pb2.AnalyzeTextRequest.SerializeToString,
            Inclusive_dot_vocab__pb2.AnalyzeTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeTargetWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vocab.VocabService/AnalyzeTargetWord',
            Inclusive_dot_vocab__pb2.AnalyzeTargetWordRequest.SerializeToString,
            Inclusive_dot_vocab__pb2.AnalyzeTargetWordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
