version: "3.8"

services:
  polyraspad:
    container_name: polyraspad
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production

  # Development version (uncomment to use)
  # polyraspad-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: builder
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next
