// <auto-generated />
using System;
using AgentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgentService.Migrations
{
    [DbContext(typeof(AgentServiceContext))]
    [Migration("20260711154939_FixPendingChanges")]
    partial class FixPendingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("internal")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentService.Data.Entities.AgentArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.HasKey("Id")
                        .HasName("agent_artifacts_pkey");

                    b.HasIndex("RunId");

                    b.HasIndex(new[] { "ThreadId", "CreatedAt" }, "idx_agent_artifacts_thread_created");

                    b.ToTable("agent_artifacts", "internal");
                });

            modelBuilder.Entity("AgentService.Data.Entities.AgentDomainDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("Allowed")
                        .HasColumnType("boolean")
                        .HasColumnName("allowed");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("UserTextPreview")
                        .HasColumnType("text")
                        .HasColumnName("user_text_preview");

                    b.HasKey("Id")
                        .HasName("agent_domain_decisions_pkey");

                    b.HasIndex(new[] { "RunId" }, "idx_agent_domain_decisions_run_id")
                        .IsUnique();

                    b.ToTable("agent_domain_decisions", "internal");
                });

            modelBuilder.Entity("AgentService.Data.Entities.AgentMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.HasKey("Id")
                        .HasName("agent_messages_pkey");

                    b.HasIndex(new[] { "ThreadId", "CreatedAt" }, "idx_agent_messages_thread_created");

                    b.ToTable("agent_messages", "internal");
                });

            modelBuilder.Entity("AgentService.Data.Entities.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.HasKey("Id")
                        .HasName("agent_runs_pkey");

                    b.HasIndex(new[] { "ThreadId" }, "idx_agent_runs_thread_id");

                    b.ToTable("agent_runs", "internal");
                });

            modelBuilder.Entity("AgentService.Data.Entities.AgentThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AgentId")
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("agent_threads_pkey");

                    b.HasIndex(new[] { "UserId", "ProjectId", "UpdatedAt" }, "idx_agent_threads_user_project_updated")
                        .IsDescending(false, false, true);

                    b.ToTable("agent_threads", "internal");
                });

            modelBuilder.Entity("AgentService.Data.Entities.AgentToolCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("output_json");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.HasKey("Id")
                        .HasName("agent_tool_calls_pkey");

                    b.HasIndex(new[] { "RunId", "CreatedAt" }, "idx_agent_tool_calls_run_created");

                    b.ToTable("agent_tool_calls", "internal");
                });

            modelBuilder.Entity("AgentService.Data.Entities.AgentArtifact", b =>
                {
                    b.HasOne("AgentService.Data.Entities.AgentRun", "Run")
                        .WithMany("Artifacts")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_artifacts_runs");

                    b.HasOne("AgentService.Data.Entities.AgentThread", "Thread")
                        .WithMany("Artifacts")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_artifacts_threads");

                    b.Navigation("Run");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AgentService.Data.Entities.AgentDomainDecision", b =>
                {
                    b.HasOne("AgentService.Data.Entities.AgentRun", "Run")
                        .WithOne("DomainDecision")
                        .HasForeignKey("AgentService.Data.Entities.AgentDomainDecision", "RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_domain_decisions_runs");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("AgentService.Data.Entities.AgentMessage", b =>
                {
                    b.HasOne("AgentService.Data.Entities.AgentThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_messages_threads");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AgentService.Data.Entities.AgentRun", b =>
                {
                    b.HasOne("AgentService.Data.Entities.AgentThread", "Thread")
                        .WithMany("Runs")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_runs_threads");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AgentService.Data.Entities.AgentToolCall", b =>
                {
                    b.HasOne("AgentService.Data.Entities.AgentRun", "Run")
                        .WithMany("ToolCalls")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_tool_calls_runs");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("AgentService.Data.Entities.AgentRun", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("DomainDecision");

                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("AgentService.Data.Entities.AgentThread", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Messages");

                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
