# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListThreads = channel.unary_unary(
                '/pvs.agent.grpc.AgentService/ListThreads',
                request_serializer=agent__pb2.ListAgentThreadsRequest.SerializeToString,
                response_deserializer=agent__pb2.ListAgentThreadsResponse.FromString,
                _registered_method=True)
        self.CreateThread = channel.unary_unary(
                '/pvs.agent.grpc.AgentService/CreateThread',
                request_serializer=agent__pb2.CreateAgentThreadRequest.SerializeToString,
                response_deserializer=agent__pb2.AgentThreadResponse.FromString,
                _registered_method=True)
        self.GetThread = channel.unary_unary(
                '/pvs.agent.grpc.AgentService/GetThread',
                request_serializer=agent__pb2.GetAgentThreadRequest.SerializeToString,
                response_deserializer=agent__pb2.AgentThreadResponse.FromString,
                _registered_method=True)
        self.ListMessages = channel.unary_unary(
                '/pvs.agent.grpc.AgentService/ListMessages',
                request_serializer=agent__pb2.ListAgentMessagesRequest.SerializeToString,
                response_deserializer=agent__pb2.ListAgentMessagesResponse.FromString,
                _registered_method=True)
        self.CreateRun = channel.unary_unary(
                '/pvs.agent.grpc.AgentService/CreateRun',
                request_serializer=agent__pb2.CreateAgentRunRequest.SerializeToString,
                response_deserializer=agent__pb2.CreateAgentRunResponse.FromString,
                _registered_method=True)
        self.ExecuteRun = channel.unary_unary(
                '/pvs.agent.grpc.AgentService/ExecuteRun',
                request_serializer=agent__pb2.ExecuteAgentRunRequest.SerializeToString,
                response_deserializer=agent__pb2.CreateAgentRunResponse.FromString,
                _registered_method=True)
        self.ArchiveThread = channel.unary_unary(
                '/pvs.agent.grpc.AgentService/ArchiveThread',
                request_serializer=agent__pb2.ArchiveAgentThreadRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateArtifact = channel.unary_unary(
                '/pvs.agent.grpc.AgentService/CreateArtifact',
                request_serializer=agent__pb2.CreateAgentArtifactRequest.SerializeToString,
                response_deserializer=agent__pb2.AgentArtifactItem.FromString,
                _registered_method=True)
        self.ListArtifacts = channel.unary_unary(
                '/pvs.agent.grpc.AgentService/ListArtifacts',
                request_serializer=agent__pb2.ListAgentArtifactsRequest.SerializeToString,
                response_deserializer=agent__pb2.ListAgentArtifactsResponse.FromString,
                _registered_method=True)
        self.ExecuteRunStream = channel.unary_stream(
                '/pvs.agent.grpc.AgentService/ExecuteRunStream',
                request_serializer=agent__pb2.ExecuteAgentRunRequest.SerializeToString,
                response_deserializer=agent__pb2.ExecuteAgentRunStreamResponse.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListThreads(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListArtifacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteRunStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListThreads': grpc.unary_unary_rpc_method_handler(
                    servicer.ListThreads,
                    request_deserializer=agent__pb2.ListAgentThreadsRequest.FromString,
                    response_serializer=agent__pb2.ListAgentThreadsResponse.SerializeToString,
            ),
            'CreateThread': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateThread,
                    request_deserializer=agent__pb2.CreateAgentThreadRequest.FromString,
                    response_serializer=agent__pb2.AgentThreadResponse.SerializeToString,
            ),
            'GetThread': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThread,
                    request_deserializer=agent__pb2.GetAgentThreadRequest.FromString,
                    response_serializer=agent__pb2.AgentThreadResponse.SerializeToString,
            ),
            'ListMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessages,
                    request_deserializer=agent__pb2.ListAgentMessagesRequest.FromString,
                    response_serializer=agent__pb2.ListAgentMessagesResponse.SerializeToString,
            ),
            'CreateRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRun,
                    request_deserializer=agent__pb2.CreateAgentRunRequest.FromString,
                    response_serializer=agent__pb2.CreateAgentRunResponse.SerializeToString,
            ),
            'ExecuteRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteRun,
                    request_deserializer=agent__pb2.ExecuteAgentRunRequest.FromString,
                    response_serializer=agent__pb2.CreateAgentRunResponse.SerializeToString,
            ),
            'ArchiveThread': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveThread,
                    request_deserializer=agent__pb2.ArchiveAgentThreadRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateArtifact,
                    request_deserializer=agent__pb2.CreateAgentArtifactRequest.FromString,
                    response_serializer=agent__pb2.AgentArtifactItem.SerializeToString,
            ),
            'ListArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListArtifacts,
                    request_deserializer=agent__pb2.ListAgentArtifactsRequest.FromString,
                    response_serializer=agent__pb2.ListAgentArtifactsResponse.SerializeToString,
            ),
            'ExecuteRunStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteRunStream,
                    request_deserializer=agent__pb2.ExecuteAgentRunRequest.FromString,
                    response_serializer=agent__pb2.ExecuteAgentRunStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pvs.agent.grpc.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pvs.agent.grpc.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListThreads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pvs.agent.grpc.AgentService/ListThreads',
            agent__pb2.ListAgentThreadsRequest.SerializeToString,
            agent__pb2.ListAgentThreadsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pvs.agent.grpc.AgentService/CreateThread',
            agent__pb2.CreateAgentThreadRequest.SerializeToString,
            agent__pb2.AgentThreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pvs.agent.grpc.AgentService/GetThread',
            agent__pb2.GetAgentThreadRequest.SerializeToString,
            agent__pb2.AgentThreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pvs.agent.grpc.AgentService/ListMessages',
            agent__pb2.ListAgentMessagesRequest.SerializeToString,
            agent__pb2.ListAgentMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pvs.agent.grpc.AgentService/CreateRun',
            agent__pb2.CreateAgentRunRequest.SerializeToString,
            agent__pb2.CreateAgentRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pvs.agent.grpc.AgentService/ExecuteRun',
            agent__pb2.ExecuteAgentRunRequest.SerializeToString,
            agent__pb2.CreateAgentRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchiveThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pvs.agent.grpc.AgentService/ArchiveThread',
            agent__pb2.ArchiveAgentThreadRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pvs.agent.grpc.AgentService/CreateArtifact',
            agent__pb2.CreateAgentArtifactRequest.SerializeToString,
            agent__pb2.AgentArtifactItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pvs.agent.grpc.AgentService/ListArtifacts',
            agent__pb2.ListAgentArtifactsRequest.SerializeToString,
            agent__pb2.ListAgentArtifactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteRunStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pvs.agent.grpc.AgentService/ExecuteRunStream',
            agent__pb2.ExecuteAgentRunRequest.SerializeToString,
            agent__pb2.ExecuteAgentRunStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
